import Layout from "@/components/Layout";
import Head from "next/head";
import { FC } from "react";

interface Props {}

const About: FC<Props> = ({}) => {
	return (
		<>
			<Head>
				<title>About | Sahand Porkar</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<main>
					<div className="px-6 container">I'm a Copenhagen based Art Director specializing in Motion and VFX. My work spans in culture and brands. I've led projects across a variety of sectors including advertisement, tech, music and art.</div>
				</main>
			</Layout>
		</>
	);
};

export default About;
