import Motion from "@/components/Motion";
import Head from "next/head";
import { FC } from "react";

interface Props {}

const About: FC<Props> = ({}) => {
	return (
		<>
			<Head>
				<title>About | Sahand Porkar</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Motion>
				<main>
					<div className="container px-4">
						<h3 className="mt-10">I'm a Copenhagen based Digital Designer, specializing in Motion and VFX. My work spans in culture and brands. I've led projects across a variety of sectors including advertisement, tech, music and art.</h3>
					</div>
				</main>
			</Motion>
		</>
	);
};

export default About;
