import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Project, Projects } from "@/data/projects";
import { ProjectTile } from "./../components/ProjectTile";

export default function Home({ projects }: Projects & Project) {
	// useEffect(() => {
	// 	projects.map((project: any) => {
	// 		console.log(project);
	// 	});
	// }, [projects]);

	return (
		<>
			<Head>
				<title>Motion & graphics designer | Sahand Porkar</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="container min-h-[65vh] flex flex-col justify-center">
				<h1 className="text-[5rem] leading-none font-medium mb-6">
					Turning ideas into <br /> visual experiences <br /> and digital solutions.
				</h1>
				{/* <h2 className="text-[2rem]">Specialising in Motion graphics, VFX and digital design.</h2> */}
				{/* <h2 className="text-[2rem] font-regular">
					Co-founder of{" "}
					<a href="https://comfortoasis.studio" target="_blank" className="underline font-medium">
						Comfort Oasis Studio
					</a>
					.
				</h2> */}
			</header>
			<main className="container">
				<h3 className="text-2xl font-medium mb-10">
					Some of my work <small>&#8600;</small>
				</h3>
				<ul className="md:grid gap-[10px] grid-cols-2 grid-rows-2">
					{projects.map((project: Project) => {
						return <ProjectTile key={project.pid} {...project} />;
					})}
				</ul>
			</main>
		</>
	);
}
